---
name: test
on: pull_request_target
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: main
          path: main
      - run: rsync --delete -a Makefile ../Makefile
        working-directory: main
      - run: rsync --delete -a scripts ../scripts
        working-directory: main
      - run: rm -Rf main
      - run: make hello
